name: ipc_app
description: IPC – Conversor 100% pixel perfect do Android para Flutter Web.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9          # para ícones SVG
  provider: ^6.1.1             # gerenciamento de estado
  google_fonts: ^6.1.0         # Times New Roman
  fl_chart: ^0.66.0            # gráficos de linha/barras
  table_calendar: ^3.0.9       # calendário interativo
  flutter_math_fork: ^0.7.2    # renderização de fórmulas (opcional)
  http: ^1.1.0                 # chamadas API (mockadas)
  lottie: ^2.7.0               # animações de loading
  intl: ^0.18.1                # formatação de datas

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/pattern/
    - assets/lottie/

  fonts:
    - family: TimesNewRoman
      fonts:
        - asset: assets/fonts/pattern/times_new_roman.ttf
          weight: 400
        - asset: assets/fonts/pattern/times_new_roman.ttf
          weight: 700
          style: normal   # se tiver bold separado, aponte para o bold.ttf